variable "compartment_id" {}
variable "project_name" {}
variable "region" {}
variable "ssh_public_key" {}
variable "freetier_ad_list" {}
variable "whitelist_subnets" {}
variable "vcn_subnet" {}
variable "private_subnet" {}
variable "public_subnet" {}